### ISSUE TITLE
Need automated tests

### ISSUE THREAD

**Issue by asmith-mdsol** [mdsol/dice_bag#16]
We need automated tests. I'm interested to know whether people prefer Cucumber-based testing as a form of documentation or to keep it close to the metal with RSpec. I'm leaning towards Cucumber (perhaps using Aruba given it's a CLI interface) because mocking out Rake's DSL looks like a nightmare. That's not to say we shouldn't unit test with RSpec where we have nicely isolated classes.

**Comment by ghost** [comment]
+1 for automated tests.  I think the question of cucumber vs rspec depends on how explicit you want to make dice_bag's functionality to a user of dice_bag.  If you feel the need to make the functionality of cucumber very explicit, then cucumber it is.  If you are okay with someone sorting through rspec to figure out what's going on, I would use rspec.

IMO, I would do rspec and then README like documentation.  Why?  Cucumber scenarios are often hard to read and figure out what is going on.

**Comment by mszenher** [comment]
I agree with Chad:  rspec + nice README.

**Comment by asmith-mdsol** [comment]
I'm closing this. We have cucumber scenarios that cover all the main functionality now. Rspec would be nice but the internals aren't really designed for testing (yet) and this bug misrepresents the state of affairs.
