### ISSUE TITLE
Open source

### ISSUE THREAD

**Issue by asmith-mdsol** [mdsol/dice_bag#17]
This should be open source. What license?

**Comment by ghost** [comment]
I don't think you have much of a choice in this one.  Last I spoke a lawyer here about license (1.5 years ago), they wanted a "permissive" license.  I take this to mean pretty much MIT or BSD.

Since much of my income and much of the tools I use in my profession are GPL, I vote GPL.

**Comment by jcarres-mdsol** [comment]
This looks good to me:
https://github.com/thoughtbot/factory_girl/blob/master/LICENSE

**Comment by asmith-mdsol** [comment]
That looks like the MIT license, which seems prevalent in Ruby gems.

**Comment by asmith-mdsol** [comment]
This is currently with legal, no reply as yet.

**Comment by asmith-mdsol** [comment]
Looks like this is going ahead, the only significant issue being finding a license the company is happy to use. I've stated my preference for MIT as it fits with the Ruby community but Apache also seems to be in favour. GPL is off the table, sorry Chad.

**Comment by asmith-mdsol** [comment]
Currently targeting mid-January.

**Comment by asmith-mdsol** [comment]
Process is almost in place. MIT will be the license unless we want to hold up for legal approval of something else (which I don't personally). I got approval to open source from @isaacwong yesterday. We'll need to add a LICENSE file and then we're good to go. Anything else we should tidy up before we release?

**Comment by jcarres-mdsol** [comment]
Awesome! 
Please make a PR for the LICENSE file, you know better what we need there. 
We will just make this repository public or create a new one?
Once it is opensource, I'll submit it to rubygems. 
There is anything we want to delete before making it public? like this discussion for instance?

**Comment by asmith-mdsol** [comment]
We'll just make this repo public. Things blocking now:
1. Announcement of policy within company. This may not actually be a blocker.
2. Is there anything undocumented we need to add to the README?
3. Quick due-diligence check of issues. I don't think we have anything to hide (including this discussion) but I should check.

**Comment by jcarres-mdsol** [comment]
I think number 2 is not a blocker, can be addressed when we discover
I think number 3 is fine.

**Comment by asmith-mdsol** [comment]
I've just made the repo public. We are open source! :smile:

**Comment by jcarres-mdsol** [comment]
:heart_eyes:
