### ISSUE TITLE
Database template should automatically pick up $BUILD_NUMBER for database name

### ISSUE THREAD

**Issue by asmith-mdsol** [mdsol/dice_bag#18]
For CI environments, we should automatically pick up Jenkins' `BUILD_NUMBER` environment variable and append it to the database name for hassle-free parallel CI runs. Possibly this should be managed in mdsol/kender instead given it's CI-specific; unsure at this time.

**Comment by jcarres-mdsol** [comment]
Or maybe it should be called TEST_ENV_NUMBER this is needed to run test in parallel. or maybe we need both? 
And it should be only there for develop and test, what is a bit of a change in our current template.

**Comment by asmith-mdsol** [comment]
I was thinking that if the configuration (environment variable) is missing it just leaves off the number. So, `my_project_db` in production but `my_project_db_123` if `BUILD_NUMBER=123`. We can use `join` in the template. If there are other "standard" environment variables to support we can just chain them all together.

**Comment by jfeltesse-mdsol** [comment]
Closing this issue since it's ancient and meanwhile 
- Jenkins is not used in ruby projects anymore at mdsol
- `TEST_ENV_NUMBER` found its way in the pre-packaged DB templates
