### ISSUE TITLE
rake config should not overwrite files by default

### ISSUE THREAD

**Issue by mjobin-mdsol** [mdsol/dice_bag#21]
rake config overwrite files with no warning... 
I think it should only push missing files automatically, display something when the file is already there.
and offer to diff/overwrite/skip when the content is different.

very much like rails do when you upgrade your app or when using the generator.

I think dice_bag is a great idea. and everywhere I saw people making .example files of their config. I think dice_bag should aimed at being very small and eventually become part of rails 4

so we should make it very much like rails does things for that reason.

**Comment by asmith-mdsol** [comment]
This is a duplicate of #12 so closing.
