### ISSUE TITLE
Accept RACK_ENV for non-Rails apps, or something else for non-Ruby apps.

### ISSUE THREAD

**Issue by harryw** [mdsol/dice_bag#25]
Dice bag [checks RAILS_ENV](https://github.com/mdsol/dice_bag/search?q=RAILS_ENV) to decide whether or not to block and wait for user input when overwriting files.  We have a number of non-Rails apps, which naturally use RACK_ENV.

Of course, it would be preferable it this was completely independent of a specific framework - we should be able to use Rake to configure just about any application, and it would be nice if Dice Bag could help with that.  This has already been mentioned as something to consider for Rave config.  How about defining a new variable that's used to make Dice Bag work in 'quiet' mode?

**Comment by asmith-mdsol** [comment]
We've been trying to make it as smart as possible, so you don't have to toggle magic switches to get the behaviour you want. See #12 for a discussion of the use cases we're trying to handle.

I'm inclined to remove the environment checking completely and just rely in `$stdin.is_tty?`.

**Comment by harryw** [comment]
If that works reliably then yeah, that's fine.  I'm not sufficiently confident in the results of #is_tty? to be opinionated about it.

**Comment by asmith-mdsol** [comment]
I've seen other tools use it but perhaps we need to check both `$stdin` and `$stdout`. Probably best to just try it out and see what happens... I think they call this "validated learning".

**Comment by mjobin-mdsol** [comment]
![PennyArcade 2004 comic](https://photos.smugmug.com/photos/215499741_EEML7-L-2.jpg)

I am in favor of this https://www.hezmatt.org/~mpalmer/blog/2013/10/13/rack_env-its-not-for-you.html

Sinatra now support APP_ENV from 2.0 http://sinatrarb.com/configuration.html

So I would vote against we do anything with RACK_ENV in this gem.

Let's open a new issue if we need to do anything real

Close coffins so skeleton don't escape

![hahaha](https://i.pinimg.com/originals/67/28/c1/6728c1aa519c0fba99e40302fddc018f.jpg)
