### ISSUE TITLE
Make it easy to choose an explicit set of files to be configured through Dice Bag

### ISSUE THREAD

**Issue by harryw** [mdsol/dice_bag#26]
For easy adoption of Dice Bag into a mature project, it would be preferable to be able to introduce Dice Bag gradually, handling just some parts of the configuration, rather than having to replace the whole configuration mechanism at once.  The automatic, smart detection approach is nice but having an easy way to specify a fixed set of config files to be handled by Dice Bag would be a useful fallback if there's any kind of problem with the opinions Dice Bag has about your config.

I've talked this through with @asmith-mdsol a bit; a .dice_bag file (or similar) was suggested as a good way to be explicit.

In the short term I have used my own Rake task that invokes the config:file[myfile.yml.erb] task, but the support for depending on tasks with arguments is limited in Rake, and this will not work easily with multiple config files.

**Comment by asmith-mdsol** [comment]
See the README in #28 and let me know if it addresses your issue here.

**Comment by harryw** [comment]
Looks good to me.
