### ISSUE TITLE
Remove/fix deprecation warnings

### ISSUE THREAD

**Issue by harryw** [mdsol/dice_bag#27]
When I run dice bag tasks I see this:

`DEPRECATION WARNING: railtie_name is deprecated and has no effect. (called from <class:Railtie> at /Users/harry/.rvm/gems/ruby-1.9.2-p290/bundler/gems/dice_bag-0e1e760e90c5/lib/dice_bag/railtie.rb:3`

It's with Rails 3.0, fwiw.

**Comment by asmith-mdsol** [comment]
Odd, not seen that in local usage... but perhaps I'm just unobservant.

**Comment by harryw** [comment]
Using railties 3.0.17 if that's relevant.

**Comment by harryw** [comment]
This now appears for _all_ Rake tasks, btw, not just the Dice Bag tasks.
