### ISSUE TITLE
Ensure brakeman task picks up local project configuration

### ISSUE THREAD

**Issue by asmith-mdsol** [mdsol/dice_bag#3]
We run brakeman to fail if there are any warnings as this is the best practice. Some projects may wish to ignore these warnings for pragmatic reasons, so we should respect any local configuration settings the project provides.

**Comment by jcarres-mdsol** [comment]
Every project can have its own .brakeman where they can specify what methods are safe or what test they do not want to pass.

**Comment by jcarres-mdsol** [comment]
I meant that by default brakeman already reads .brakeman and honore it, so I think this is a non issue and I close it.

**Comment by asmith-mdsol** [comment]
I'm going to re-open until we have this documented for users.

**Comment by asmith-mdsol** [comment]
Moved to mdsol/kender#9.
