### ISSUE TITLE
Dice Bag ignores directories beginning with '.'

### ISSUE THREAD

**Issue by harryw** [mdsol/dice_bag#69]
Raising this just because I am not sure if it's intentional.

Dice Bag does not generate config files from *.dice files under a dot-prefixed directory. The root of this appears to be Project#templates_to_generate:

``` ruby
    def self.templates_to_generate
      Dir['**/*.dice']
    end
```

I believe this is omitting dot-prefixed directories.

Is this desired behaviour?

**Comment by mjobin-mdsol** [comment]
I'd hope no ones wants templates under dot-prefixed directories, but that's only my opinion...

**Comment by asmith-mdsol** [comment]
It's not an intentional omission but perhaps we should be careful of directories like `.git` if only for performance reasons. Did you have a use case in mind?

**Comment by harryw** [comment]
I was testing vendored gems under a dot-prefixed directory and discovered this behaviour.

I'm not really lobbying for or against the behaviour, but I don't think it's implicit that this is a feature.

If this is how Dice Bag is expected to work, it should probably be documented and perhaps tested. But it's not that big a deal. I might add a test in the course of making another change.

**Comment by asmith-mdsol** [comment]
Interesting! I've done similar things with bundler installing to `./.bundle` myself in the past. I think at the very least it should be documented. I'm inclined to leave the behaviour as it is because I feel there's an expectation that dot-directories are for private use.

**Comment by johngluckmdsol** [comment]
Why is this still open?

**Comment by jfeltesse-mdsol** [comment]
That issue from 4 years ago has been resolved by the referenced PR also from 4 years ago, it's still open because obviously they forgot to close, nothing else.
