### ISSUE TITLE
Split out CI tasks into separate gem?

### ISSUE THREAD

**Issue by asmith-mdsol** [mdsol/dice_bag#7]
We would like to make this gem pull in dependencies like brakeman (see #2) but one of the goals for this gem is to be used in production configuration. We don't want to have to install testing / CI gems in production just to do configuration. Should we split out the CI tasks into a separate gem that can have its own dependencies?

**Comment by harryw** [comment]
Yes, I think it makes sense to split the two use cases.

**Comment by asmith-mdsol** [comment]
The CI gem will go into the as-yet uncreated mdsol/kender repo.

**Comment by asmith-mdsol** [comment]
This has been done, see mdsol/kender.
