### ISSUE TITLE
Be louder about `bundle exec rake config:all` deprecation

### ISSUE THREAD

**Issue by johngluckmdsol** [mdsol/dice_bag#89]
If you are deprecating this, you should let people know and advise them what to use instead

**Comment by jfeltesse-mdsol** [comment]
Assuming you're referring to [this comment](https://github.com/mdsol/dice_bag/blob/develop/lib/dice_bag/tasks/config.rake#L10) I think what it means is calling it using `config:all` is deprecated but I can't be sure, I'm not the author.

Please give more details if I didn't guess correctly.

**Comment by johngluckmdsol** [comment]
Yes, this it the comment to which I am referring

**Comment by jfeltesse-mdsol** [comment]
That comment is 5 years old, I don't think that deprecation comment means much...
Sure, the docs and usage don't talk about `config:all` and favor `config` so I guess you could say that's the preferred usage.

If you feel the command should be more vocal about this, PRs are welcome. There's no single team owning dice_bag. Whoever needs a new feature or finds a bug is welcome to contribute.

Closing this issue because I think all has been said. Feel free to re-open if needs be.

**Comment by johngluckmdsol** [comment]
Hey @jfeltesse-mdsol , I apologize for reopening but I don't think we're yet at the bottom of this.  

How about this proposal?  Since this command is supposedly deprecated, let's remove it.  Do you understand what that would entail, because I don't.

If not, let's remove/modify the comment. Let's remove the comment if we aren't ever realistically going to remove the task.  Let's modify if we are going to deprecate it to let people know what they should use instead and who to contact since it has been 5 years. We need to remove it from our own codebase probably before we do that.

https://github.com/search?l=Ruby&q=org%3Amdsol+%22config%3Aall%22&type=Code

I understand we can't possibly know if anyone is using it given the lack of telemetry, but it still appears in our own code base, so until there is an orchestrated effort to remove it from own code base, we can't possibly deprecate it for the public.  

If we are following semantic version rules, that will force a major revision because removing a rake task is not a backward compatible change

I'm interested in hearing your opinion.  Perhaps what we should do is keep this open and open an additional task to add telemetry to to this gem to find out how often the task is being used

**Comment by cabbott** [comment]
@johngluckmdsol let's remove that old comment, or change it to state its an alias and that ```config``` is preferred over ```config:all```
I don't think we should make a major version bump for something that isn't broken and not problematic at this point
